### ISSUE TITLE
Blacklisting

### ISSUE THREAD

**Issue by Lytorphan** [dogkisser/goonto#15]
Hey,

I'm bad, really bad at Github, so I have no idea if I'm writing this in the right place. But anyway, it would be really nice to be able to blacklist tags.

**Comment by dogkisser** [comment]
Hey!

This isn't really the best place just because I rarely check Issues if I'm not actively working on something, so you might not get a timely response (see: now). You'd be better served DMing me on [Eks dot com](https://twitter.com/zoomasochist)

As for your question, `tags-prefix`/`tags` supports regular 'ol e621 search syntax, so you could do this to blacklist a tag for every set of `tags`:

```yaml
tags-prefix: -cub score:>200 rating:explicit
```

or similarly to blacklist tags for just one `tags` entry:

```yaml
tags:
  - female nike_high_tops
  - male -nike_high_tops
```

Is that kinda what you're looking for?

**Comment by dogkisser** [comment]
awa
