### ISSUE TITLE
Troubles with Starting Program

### ISSUE THREAD

**Issue by YvesStephen** [dogkisser/goonto#19]
I'm new to using GitHub, so I'm not sure if I'm doing anything right or wrong, but I am having trouble locating and running the program, as I don't see any .exe file. Idk if I'm downloading wrong or need to have another program but help would be greatly appreciated

**Comment by Skillfullyunskillfull** [comment]
Despite what is says in their [FAQ](https://github.com/dogkisser/goonto/wiki/FAQ), the maintainers of this Repository seemingly do not have any .exe files as of 11/7/24. That means that you're going to have to make your own (kinda).

 The steps to do this should be as follows:
1. Get and install Rust and the Rust nightly build
2. Get Goonto
3. Build Goonto
4. Profit in your own cyber-degeneracy
5. 
**Note that you will have to download install (probably more than 1Gb) some things in order to build the exe yourself.**

# Get Rust
## Download Rustup-init.exe
Below are links to download rustup, the rust installer. Choose one depending on whether you have a 32-bit or 64-bit system. If you don't know, then [this](https://www.intowindows.com/how-to-check-if-your-pc-is-running-32-bit-or-64-bit-windows-10/) website will help you find out.

[Download rustup-init.exe (32-bit)](https://static.rust-lang.org/rustup/dist/i686-pc-windows-msvc/rustup-init.exe)
[Download rustup-init.exe (64-bit)](https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe)

## Install Rust
Once you've downloaded and ran `rustup-init.exe`, you'll probably see this:
![image](https://github.com/user-attachments/assets/8af7cd3f-59ef-45ea-9334-b81fd4a45dda)
Of the three options here, 1 is the quickest, but know that it will install a code editor called "Visual Studio" in order to do its job. If you don't want this, then you'll have to install the prerequisites manually [2] (more info [here](https://rust-lang.github.io/rustup/installation/windows.html) .) Otherwise press 1.

You should soon see a visual studio window pop up and ask you about its installation. 
**Ensure** that the two MSVC.... and Windows 10/11 SDK boxes are check. If they aren't, they will not install and the program will **not** compile correctly:
![image](https://github.com/user-attachments/assets/f872aa12-6f4b-4077-9c43-0019d04e3cfa)

Once you've clicked through that and gotten that installed, you should be faced with this on your cmd:
![image](https://github.com/user-attachments/assets/0f3b8384-a302-4639-b3c7-471f53034ad5)

Pressing 'Enter' should do the trick, then the installer will start downloading and installing a bunch of Rust tools (clippy, cargo, rustc). This'll take maybe 10-15 minutes depending on your Internet speed n' such.

Once that's done it'll say that Rust is installed and then auto-close. However we need to install the nightly build of Rust for this program. You will need to open the Windows search bar and search for "command prompt" and open it. Then type in `rustup toolchain install nightly` and press enter. This will take a little bit.

Once that's done go ahead and type in `rustup default nightly` and press enter. Then type in `cargo update`.
Congrats: hard part over.

#Get Goonto
##Download Goonto
On the Goonto Github page, click on the green "<> code v" button, then click on "Download ZIP".
![image](https://github.com/user-attachments/assets/5986ce23-f98d-42a6-b02b-74e288f8f610)

Once that's installed, unzip it and open the "goonto-master" folder.

#Compile Goonto (make the executable)
Now that you have the goonto-master folder open in file explorer, open a command prompt if you don't have one open already.

Now go back to the goonto folder you have open, and copy the file path:
![image](https://github.com/user-attachments/assets/45551474-c607-488b-b004-8bffda76983e)

Now go back to the command prompt and type "cd", then paste your copied path:
![image](https://github.com/user-attachments/assets/6bad1269-fb29-4751-ad5a-8286bdbf2f34)

Press enter, and then enter in "cargo build --release". Once you press enter it will compile (make) the program/.exe.
When it's done, you can type `cd target\release\goonto` to enter the exact folder where the goonto.ex is, or you can navigate there using your file explorer (wherever you put the goonto-master folder + target\release\goonto).

Enjoy.

**Comment by dogkisser** [comment]
Ya the repo was banned before because you could click a binary and immediately see porn without a consent popup, so I deleted them as a precaution. I think if I make a new release it'll start building again, otherwise I might have to fiddle with the workflows. Sorry for the trouble :3~

**Comment by dogkisser** [comment]
https://github.com/dogkisser/goonto/releases/tag/v2.0.0
